version: "3.7"
services:
  db:
    container_name: "digital-menu"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: chico
      MYSQL_PASSWORD: Arhena300
      MYSQL_ROOT_PASSWORD: arena200
      MYSQL_DB: digital_menu

    volumes:
      - ./init:/docker-entrypoint-initdb.d
